# Render.com Blueprint for Python Web Service
services:
  - type: web
    name: bank-to-splitwise
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
    autoDeploy: true
